#!/bin/bash

# Make sure we are not running as root, but that we have sudo privileges.
if [ "$(id -u)" = "0" ]; then
   echo "This script must NOT be run as root (or with sudo)!"
   exit 1
elif [ "$(sudo -l | grep '(ALL : ALL) ALL' | wc -l)" = 0 ]; then
   echo "You do not have enough sudo privileges!"
   exit 1
fi
cd ~; sudo pwd # Print Working Directory; have the user enable sudo access if not already.

# Give the user pertinent information about this script and how to use it.
cat << EOF | sudo tee ~/readme.txt
This readme was generated by the "satoshi-coins.sh" install script.

Script installs a "Satoshi Coins Explorer" where information for a specific coin can be found if that
coin was produced by this "microbank" providing the service. Also, a cron job is setup to run every day at
4:00 AM to update the database if there were any new coins added to a specified chain (see coins.ini file).

The "/var/www/html" directory contains the PHP powered website.
Modify the "/var/www/html/coins.ini" file to add more Satoshi Coins' chains.
    Note: The file contains additional information.
Use the following commands to rebuild or update the Satohi Coins' database:
    (cd /var/www/html && sudo -u www-data php -r "require 'admin.php'; adminCMD('UPDATE');"; echo "")   # Updates the database
    (cd /var/www/html && sudo -u www-data php -r "require 'admin.php'; adminCMD('BUILD');"; echo "")    # Rebuilds the database
    (cd /var/www/html && sudo -u www-data php -r "require 'index.php';"; echo "")                       # Run index.php to look for errors (for development)

Other commands that may be of interest:
    php -v                                          # Show PHP version
    php -m                                          # Show PHP modules loaded
    sqlite3 /var/www/html/db.sqlite3 ".dump"        # Dumps the SQLITE Database

View php information from the web browser
    ssh -L 9093:localhost:80 satoshi@satoshi-coins.local -i \$HOME\.ssh\YubiKey # Must first login with port forwarding
    Web Address: localhost:9093/admin/info.php
EOF

# Run latest updates and upgrades
sudo apt-get -y update
sudo DEBIAN_FRONTEND=noninteractive apt-get -y install --only-upgrade openssh-server # Upgrade seperatly to ensure non-interactive mode
sudo apt-get -y upgrade

# Install Packages
sudo apt-get -y install apache2 php sqlite3

sudo apt-get -y install php-fpm                 # Alternative implementation of PHP's FastCGI
sudo apt-get -y install libapache2-mod-php      # PHP module for Apache 2 webserver
sudo apt-get -y install libapache2-mod-fcgid    # High-performance alternative to PHP's mod_cgi(d) for Apache 2 webserver

sudo apt-get -y install php-curl                # Performs remote request operations.
sudo apt-get -y install php-mbstring            # Used to properly handle UTF8 text.
sudo apt-get -y install php-bcmath              # For arbitrary precision mathematics, which supports numbers of any size and precision up to 2147483647 decimal digits.

sudo apt-get -y install php-cli                 # PHP Command Line Interface
sudo apt-get -y install php-sqlite3             # PHP SQLite Support

sudo apt-get -y install php-apcu                # PHP object caching functionality
sudo apt-get -y install php-phpseclib           # PHP Secure Communications Library

# Load global environment variables
source ~/globals.env

# Authorize Yubikey login for satoshi
echo $YUBIKEY | sudo tee -a ~/.ssh/authorized_keys

# Install Satoshi Coins' Website
cd ~; git clone https://github.com/satoshiware/satoshi-coins
sudo mv ~/satoshi-coins/website/* /var/www/html
sudo mkdir -p /var/www/html/admin
echo "<?php phpinfo(); ?>" | sudo tee /var/www/html/admin/info.php
sudo mv /var/www/html/index.html /var/www/html/index.html.original
sudo chown -R www-data:www-data /var/www/html
sudo chmod -R 755 /var/www/html
rm -rf ~/satoshi-coins

# Write global verialbes to the /var/www/html/coins.ini file
sudo sed -i "s/\$MICRO_BANK_NAME/$MICRO_BANK_NAME/g" /var/www/html/coins.ini
sudo sed -i "s/\$BTC_EXPLORER/${BTC_EXPLORER//\//\\/}/g" /var/www/html/coins.ini
sudo sed -i "s/\$BTC_ELECTRUM/${BTC_ELECTRUM//\//\\/}/g" /var/www/html/coins.ini

# Generate Apache 2 configuration file
cat << EOF | sudo tee /etc/apache2/sites-available/000-default.conf
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    ServerName satoshi-coins
    DocumentRoot /var/www/html
    ErrorLog \${APACHE_LOG_DIR}/error.log
    CustomLog \${APACHE_LOG_DIR}/access.log combined
    <Directory /var/www/html>
        AllowOverride All
    </Directory>
    <Directory /var/www/html/admin>
        Require local
    </Directory>
</VirtualHost>
EOF

# Configure apache 2 w/ php and restart
sudo systemctl stop apache2
sudo a2dismod --force autoindex # Disable directory listings
sudo a2enmod rewrite

sudo a2dismod php"$(php --version | head -n 1 | cut -d " " -f 2 | cut -d "." -f 1,2)" # Disable latest version of php
sudo a2dismod mpm_prefork
sudo a2dismod mpm_worker

sudo a2enmod mpm_event

sudo a2enconf php*-fpm
sudo a2enmod proxy
sudo a2enmod proxy_fcgi

sudo systemctl restart apache2

# Build the database
(cd /var/www/html && sudo -u www-data php -r "require 'admin.php'; adminCMD('BUILD');"; echo "")

# Create a script to update the Satoshi Coins database; Add (root) Cron Job (Every 24 Hours @ 4:00 AM) to run that script
echo '#!/bin/bash' | sudo tee /usr/local/sbin/update_satoshi_coins_db > /dev/null # Use single quotes for the exclamation mark
echo "cd /var/www/html" | sudo tee -a /usr/local/sbin/update_satoshi_coins_db > /dev/null
echo "sudo -u www-data php -r \"require 'admin.php'; adminCMD('UPDATE');\"" | sudo tee -a /usr/local/sbin/update_satoshi_coins_db > /dev/null
echo "echo \"\"" | sudo tee -a /usr/local/sbin/update_satoshi_coins_db > /dev/null
sudo chmod +x /usr/local/sbin/update_satoshi_coins_db

(crontab -l | grep -v -F "/usr/local/sbin/update_satoshi_coins_db" ; echo "0 0 4 * * /usr/local/sbin/update_satoshi_coins_db" ) | crontab -

# Create link (for backup purposes) to coins.ini
cd ~; mkdir backup
sudo ln -s /var/www/html/coins.ini ~/backup

# If "~/restore" folder is present then restore the coins.ini file
if [[ -d ~/restore ]]; then
    # Restore ownership
    sudo chown www-data:www-data ~/restore/coins.ini

    # Move file to correct location
    sudo mv ~/restore/coins.ini /var/www/html/coins.ini

    # Remove the "~/restore" folder
    cd ~; sudo rm -rf restore

    # Rebuild the database
    (cd /var/www/html && sudo -u www-data php -r "require 'admin.php'; adminCMD('BUILD');"; echo "")
fi

# Clean up
sudo rm ~/globals.env
sudo rm -rf ~/microbank

# Restart the machine
sudo reboot now
