#!/bin/bash

# Check for BookWorm version; only continue if not BookWorm.
if [[ $(lsb_release -r | grep "Release:" | cut -d ':' -f 2 | xargs) -eq 12 ]]; then
   echo ""; echo "The latest BookWorm Version of the Raspberry Pi OS has a gcc bug."
   echo "It will not be able to successfully compile cgminer."; echo ""
   exit 1
fi

# Make sure we are not running as root, but that we have sudo privileges.
if [ "$(id -u)" = "0" ]; then
   echo "This script must NOT be run as root (or with sudo)!"
   echo "if you need to create a sudo user (e.g. satoshi), run the following commands:"
   echo "   sudo adduser satoshi"
   echo "   sudo usermod -aG sudo satoshi"
   echo "   sudo su satoshi # Switch to the new user"
   exit 1
elif [ "$(sudo -l | grep '(ALL : ALL) ALL' | wc -l)" = 0 ]; then
   echo "You do not have enough sudo privileges!"
   exit 1
fi
cd ~; sudo pwd # Print Working Directory; have the user enable sudo access if not already.

# Give the user pertinent information about this script and how to use it.
cat << EOF | sudo tee ~/readme.txt
This readme was generated by the "gekko_host.sh" install script.
This script creates a host (using cgminer) to operate miners produced by Gekko Science.

Once setup and running, connect miners to this host and they will automatically start running.

Direct your web browser to "http://$(hostname).local" to see mining stats.
See cgminer log on the web server @ http://$(hostname).local/log.html (updated every 5 minutes)
See latest cgminer screen shot @ http://$(hostname).local/screen.html (updated every 5 minutes)

FYI:
    The "$USER/.ssh/authorized_keys" file contains administrator login keys.
    The "/etc/cgminer.conf" file contains the cgminer configuration
    sudo systemctl status cgminer # View the running status of cgminer
    /var/log/cgminer/cgminer.log
    Support webpage: https://kano.is/gekko.php
EOF
read -p "Press the enter key to continue..."

# Create .ssh folder and authorized_keys file if it does not exist
if ! [ -f ~/.ssh/authorized_keys ]; then
    sudo mkdir -p ~/.ssh
    sudo touch ~/.ssh/authorized_keys
    sudo chown -R $USER:$USER ~/.ssh
    sudo chmod 700 ~/.ssh
    sudo chmod 600 ~/.ssh/authorized_keys
fi

# Run latest updates and upgrades
sudo apt-get -y update
sudo DEBIAN_FRONTEND=noninteractive apt-get -y install --only-upgrade openssh-server # Upgrade seperatly to ensure non-interactive mode
sudo apt-get -y upgrade

# Install needed packages
sudo apt-get -y install build-essential autoconf automake libtool pkg-config libcurl4-openssl-dev libudev-dev libusb-1.0-0-dev libncurses5-dev zlib1g-dev git
sudo apt-get -y install screen apache2 php

# Download, Compile, and Install cgminer
cd ~
git clone https://github.com/kanoi/cgminer
cd cgminer
CFLAGS="-O2 -march=native -fcommon" ./autogen.sh --enable-gekko --enable-icarus
make
sudo make install

# Collect Parameters
read -p "Stratum Mining Pool (i.e. \"stratum+tcp://stratum.local:3333\"): "; STRATUMPOOL=$REPLY
read -p "Name for This Mining Host (i.e. \"MyGekkos\"): "; NAME=$REPLY

# Get IPv4 range for this local private network
PNETWORK=$(echo $(hostname -I) | cut -d '.' -f 1)
if [[ ${PNETWORK} = "192" ]]; then
    PNETWORK="192.168.0.0/16"
elif [[ ${PNETWORK} = "172" ]]; then
    PNETWORK="172.16.0.0/12"
elif [[ ${PNETWORK} = "10" ]]; then
    PNETWORK="10.0.0.0/8"
fi

# Write configuration file
cat << EOF | sudo tee /etc/cgminer.conf
{
    "pools" : [
        {
            "url" : "${STRATUMPOOL}",
            "user" : "${NAME}",
            "pass" : "x"
        }
    ],
    "gekko-compaca1-start-freq" : "300",
    "gekko-compaca1-freq" : "300",
    "gekko-compaca1-corev" : "300",
    "gekko-compaca1-detect" : true,
    "gekko-r909-freq" : "450",
    "gekko-r909-detect" : true,
    "gekko-compacf-freq" : "400",
    "gekko-compacf-detect" : true,
    "gekko-tune2" : "60",
    "suggest-diff" : "442",
    "failover-only" : true,
    "api-listen" : true,
    "api-port" : "4028",
    "api-allow" : "W:${PNETWORK},W:127.0.0.1"
}
EOF
sudo chmod 440 /etc/cgminer.conf

# Create ckpool Log Folders
sudo mkdir -p /var/log/cgminer
sudo chmod 670 -R /var/log/cgminer
sudo touch /var/log/cgminer/cgminer.log

# Configure cgminer's Log Files; Prevents them from Filling up the Partition
cat << EOF | sudo tee /etc/logrotate.d/cgminer
/var/log/cgminer/cgminer.log {
$(printf '\t')create 644 root root
$(printf '\t')daily
$(printf '\t')rotate 14
$(printf '\t')compress
$(printf '\t')delaycompress
$(printf '\t')sharedscripts
}
EOF

# Copy webpage for cgminer monitoring (miner.php)
sudo cp -v ~/cgminer/miner.php /var/www/html/

# Setup miner php configuration file (myminer.php)
cat << EOF | sudo tee /var/www/html/myminer.php
<?php
\$rigs = array('127.0.0.1:4028:MyGekkos');
\$readonly = true;
\$allowgen = true;
\$rigbuttons = false;
\$rigipsecurity = false;
\$customsummarypages = array('Gekko' => 1, 'GekkoChips' => 1);
?>
EOF

# Setup default webpage with links to the logs, cgminer screen shot, and the active cgminer monitor written in php
cat << EOF | sudo tee /var/www/html/index.html
See <a href="http://$(hostname -I | grep -Eo '([0-9]*\.){3}[0-9]*' | tr '\n' '\n')/log.html" target="_blank">LOGS</a><br>
See <a href="http://$(hostname -I | grep -Eo '([0-9]*\.){3}[0-9]*' | tr '\n' '\n')/screen.html" target="_blank">CGMINER</a><br>
See <a href="http://$(hostname -I | grep -Eo '([0-9]*\.){3}[0-9]*' | tr '\n' '\n')/miner.php?ref=0&pg=Gekko" target="_blank">WEBSITE</a><br>
EOF

# Reload and Restart Apache2
echo "ServerName localhost" | sudo tee -a /etc/apache2/apache2.conf
sudo systemctl reload apache2
sudo systemctl restart apache2

# Install the cgminer control script (cgctl)
bash ~/microbank/scripts/pre_fork_micro/cgctl.sh --install

# Remove the download when finished
sudo rm -rf ~/cgminer
